services:
  web:
    build: .
    ports: 
      - 8000:8000
    environment:
      MONGO_URI: "mongodb://root:pass@mongo:27017"
      DB_NAME: "apart"
    develop:
      watch:
       - action: sync
         path: .
         target: /code
       - action: rebuild
         path: pyproject.toml poetry.lock

  mongo:
    image: "mongo"
    restart: always
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass


  mongo-express:
    image: mongo-express
    restart: always
    ports: 
      - 8082:8081
    environment: 
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: "mongodb://root:pass@mongo:27017"
      ME_CONFIG_BASICAUTH: false

